### ISSUE TITLE
ServiceTypes enum and colons

### ISSUE THREAD

**Issue by redmitry** [CSCfi/beacon-network#52]
Hello,

There is a change in the enumeration between 0.2.0 and 0.3.0.
Java JSONB API has issues as it MUST comply with Java enum rules (ugly, agree).

Is there any chance to change it to something more java friendly?

Kind regards,

dmitry

**Comment by teemukataja** [comment]
Beacon Network is following [GA4GH Discovery](https://github.com/ga4gh-discovery/ga4gh-service-registry) specification and naming conventions, hence the colons.
