### ISSUE TITLE
Authorise registration with an access token

### ISSUE THREAD

**Issue by teemukataja** [CSCfi/beacon-network#62]
#### Proposed solution
`Registry POST /services` is now authorised with an `Authorization` header. Consider a possibility to authorise registration with an access token (e.g. ELIXIR AAI issued JWT).

#### DoD (Definition of Done)
`Registry POST /services` will check for both header cases `Authorization: apikey` and `Authorization: Bearer accesstoken`. Api key is checked from DB as per usual, Bearer-token should be validated from AAI issuer.

#### Testing
* Unit tests
* Integration tests

**Comment by blankdots** [comment]
this has Elixir AAI as an external dependency to have a claim  in the JWT to allow to register beacons, for now this is not required.
